/* eslint-disable */

export const INCREMENT_NUM = "INCREMENT";
export const DECREMENT_NUM = "DECREMENT";
export const RESET = "RESET";
export const SET_COUTNER_VALUE = "SET_COUNTER_VALUE";
export const INC_REQUEST_COUNT = "INC_REQUEST_COUNT";
export const TOGGLE_INC_BTN_PAUSE = "TOGGLE_INC_BTN_PAUSE";
export const TOGGLE_DEC_BTN_PAUSE = "TOGGLE_DEC_BTN_PAUSE";
export const TOGGLE_CONTROLS_PANEL = "TOGGLE_CONTROLS_PANEL";
// pattern
export const INCREMENT_PATTERN = "INCREMENT_PATTERN";
export const DECREMENT_PATTERN = "DECREMENT_PATTERN";
export const RESET_PATTERN = "RESET_PATTERN";
export const APPEND_PATTERN_MODAL = "APPEND_PATTERN_MODAL";
export const REMOVE_PATTERN_MODAL = "REMOVE_PATTERN_MODAL";

/* eslint-enable */
